# Generated by Django 4.2.7 on 2023-12-18 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndeleche', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='resume',
            field=models.FileField(default='NDELECHEHAMISNEW.pdf', upload_to='resume/'),
        ),
    ]
