# Generated by Django 4.2.7 on 2023-11-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndeleche', '0002_alter_home_greetings_1_alter_home_greetings_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('feedback', models.TextField()),
            ],
        ),
    ]
